version: '3.8'

services:

  vulnerable_web:
    build: ./vulnerable-web
    container_name: vulnerable_web
    ports:
      - "8080:80"
    networks:
      - app_network

  attacker:
    build: ./malicious-web
    container_name: attacker_web
    ports:
      - "8082:80"
    networks:
      - app_network


networks:
    app_network:
      driver: bridge